services:
  db:
    image: postgres:17-alpine
    container_name: microtask-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microtask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microtask-net
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: microtask-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microtask-net

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  microtask-net:
    driver: bridge