services:
  db:
    image: postgres:17-alpine
    container_name: microtask-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microtask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microtask-net

volumes:
  postgres_data:

networks:
  microtask-net:
    driver: bridge